In [2]:
import numpy as np
a = np.array((1,2,3,4))
list_a = [1,2,3,4]
b = np.array(list_a)
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [6]:
a = np.array([[1,2,3],[10,20,30]])
b = np.array(('a','b','c'))
c = np.array([[1.5,3],[2,5],(3.5,7.)])
print(a)
print(b)
print(c)

[[ 1  2  3]
 [10 20 30]]
['a' 'b' 'c']
[[1.5 3. ]
 [2.  5. ]
 [3.5 7. ]]


In [9]:
a = np.zeros((3,3))
b = np.ones((2,5))
print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
a = np.zeros((3,3),dtype=int)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [17]:
a = np.full((3,3),5.0,dtype=int)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [22]:
a = np.arange(10) #เหมือน range ใน python
b = np.arange(1,10,2,dtype=float)
print(type(a))
print(a)
print(b)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[1. 3. 5. 7. 9.]


In [20]:
a = np.linspace(1,50) #ถ้าไม่ใส่จำนวนข้อมูล default = 50 ตัว
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [24]:
a = np.linspace(1,5,7,dtype=int)
print(a)

[1 1 2 3 3 4 5]


In [25]:
a = np.eye(3) #diagonal matrix (เมตริกซ์ทแยงมุม)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
a = np.eye(4,3)
b = np.eye(4,3,2,dtype=int) #ตัวสุดท้ายบอกตำแหน่งเริ่มต้นของค่าทแยงมุม เป็น + เริ่มที่แถวแรก เป็น - เริ่มที่หลักแรก
print(a)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [83]:
a = np.empty((3,3)) #สุ่มเลขตามมิติที่กำหนด
b = np.empty((4,3),dtype=int)
c = np.empty((2,4),dtype=float)
print(a)
print(b)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  6.26475239e-321  0.00000000e+000 -1.14078494e-310]]


In [89]:
a = np.random.randint(100)
b = np.random.randint(100,size=(2,3))
print(a)
print(b)

71
[[66 21 72]
 [88 14 37]]


In [88]:
a = np.random.rand() #สุ่มตั้งแต่ 0-1
b = np.random.rand(2,3)
print(a)
print(b)

0.24014704309619572
[[0.15102613 0.00449967 0.50206117]
 [0.93838897 0.13722057 0.50809564]]


In [4]:
from numpy import random as rd
a = rd.choice([1,3,5,7,9,11,13,15,17,19])
b = rd.choice([1,3,5,7,9,11,13,15,17,19],size=(2,3))
c = rd.choice(rd.randint(10),size=(2,3))
d = rd.choice([1,3,5,7],p=[0.2,0.15,0.5,0.15],size=(2,3)) #กำหนดการกระจายแบบสุ่มด้วย random distribution
print(a)
print(b)
print(c)
print(d)

13
[[19 13  9]
 [ 1  3  3]]
[[1 1 2]
 [0 2 5]]
[[5 3 7]
 [7 5 5]]


In [99]:
a = np.arange(10)
rd.shuffle(a)
print(a)

[6 9 1 5 4 2 3 7 0 8]


In [101]:
a = np.arange(10)
b = rd.permutation(a)
print(b)

[6 9 4 2 8 5 1 0 3 7]


In [103]:
a = np.arange(50).reshape(5,10)
b = np.arange(5).reshape(5,1)
c = a*b
print(a)
print(b)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[  0   0   0   0   0   0   0   0   0   0]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 40  42  44  46  48  50  52  54  56  58]
 [ 90  93  96  99 102 105 108 111 114 117]
 [160 164 168 172 176 180 184 188 192 196]]


In [104]:
a = np.arange(12).reshape(3,4)
print(a)
print(a[2])
print(a[2,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
9


In [107]:
a = np.arange(24).reshape(4,3,2)
print(a)
print(a[1:3:2,1::1])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[[ 8  9]
  [10 11]]]


In [10]:
a = np.arange(12).reshape(4,3)
print(a)
idx1 = np.array([3,1,1,0,2])
print(idx1)
print(a[idx1]) #ต้องการแถวไหน
idx2 = np.array([2,2,2,2,1])
print(a[idx1,idx2]) #ต้องการแถวไหน หลักไหน

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[3 1 1 0 2]
[[ 9 10 11]
 [ 3  4  5]
 [ 3  4  5]
 [ 0  1  2]
 [ 6  7  8]]
[11  5  5  2  7]


In [13]:
a = np.arange(12).reshape(4,3)
cond = np.array([True,False,True,True])
print(a)
print(a[a<8])
print(a[cond])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2 3 4 5 6 7]
[[ 0  1  2]
 [ 6  7  8]
 [ 9 10 11]]


In [15]:
a = np.array([2.0,7.55,98,0.697,3.14])
print(np.round(a)) #ทั้งปัดขึ้น ปัดลง
print(np.round(a,1))
print(np.round(a,-1))
print(np.ceil(a)) #ปัดขึ้น
print(np.floor(a)) #ปัดลง

[ 2.  8. 98.  1.  3.]
[ 2.   7.6 98.   0.7  3.1]
[  0.  10. 100.   0.   0.]
[ 2.  8. 98.  1.  4.]
[ 2.  7. 98.  0.  3.]


In [16]:
a = np.array([-1,-2,-3])
print(np.abs(a))

[1 2 3]


In [17]:
a = np.array([1,1,3,4])
print(np.log(a)) #ฐานe
print(np.exp(a)) #ฐานe

[0.         0.         1.09861229 1.38629436]
[ 2.71828183  2.71828183 20.08553692 54.59815003]


In [18]:
a = np.arange(4,11)
print(a)
print(np.power(a,2))
print(np.log2(a))
print(np.log10(a))

[ 4  5  6  7  8  9 10]
[ 16  25  36  49  64  81 100]
[2.         2.32192809 2.5849625  2.80735492 3.         3.169925
 3.32192809]
[0.60205999 0.69897    0.77815125 0.84509804 0.90308999 0.95424251
 1.        ]


In [19]:
a = np.arange(12).reshape(4,3)
print(a)
print("sum by column : ", a.sum(axis=0))
print("sum by row : ", a.sum(axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
sum by column :  [18 22 26]
sum by row :  [ 3 12 21 30]


In [20]:
a = np.array([1,4,9,16])
print(np.sqrt(a))

[1. 2. 3. 4.]


In [23]:
a = np.array([1,1,3,4])
b = np.array([1,0,0,4])
print("NOT a",np.logical_not(a))
print("a XOR b",np.logical_xor(a,b))
print("a OR b",np.logical_or(a,b))
print("a AND b",np.logical_and(a,b))

NOT a [False False False False]
a XOR b [False  True  True False]
a OR b [ True  True  True  True]
a AND b [ True False False  True]


In [24]:
a = np.array([1,4,9,16])
print(np.all(a>5))
print(np.any(a>5))

False
True


In [25]:
a = rd.randint(4,12,size=10)
print(a)
print("min : ",np.min(a))
print("max : ",np.max(a))
print("median : ",np.median(a))
print("mean : ",np.mean(a))

[ 4 11  4  9 10 10  5  4  5 11]
min :  4
max :  11
median :  7.0
mean :  7.3


In [27]:
a = rd.randint(4,12,size=10).reshape(2,5)
print(a)
print("min : ",np.min(a,axis=1))
print("max : ",np.max(a,axis=1))
print("median : ",np.median(a,axis=1))
print("mean : ",np.mean(a,axis=1))

[[ 8 10  8  8  9]
 [ 6  9  8  6  9]]
min :  [8 6]
max :  [10  9]
median :  [8. 8.]
mean :  [8.6 7.6]


In [28]:
a = rd.randint(4,12,size=10)
print(a)
print(np.sort(a))

[ 9  9 10  4  4  7  6 10 11  5]
[ 4  4  5  6  7  9  9 10 10 11]


In [29]:
a = rd.randint(4,12,size=12).reshape(4,3)
print(a)
print(np.sort(a,axis=0))

[[11  7 10]
 [ 5  4  5]
 [ 6  6  8]
 [ 8  5  9]]
[[ 5  4  5]
 [ 6  5  8]
 [ 8  6  9]
 [11  7 10]]
